
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib'

interface ContractData {
    userName: string
    planName: string
    amount: number
    startDate: string
    endDate: string
}

export async function generateContractPdf(data: ContractData): Promise<Buffer> {
    const pdfDoc = await PDFDocument.create()
    const page = pdfDoc.addPage()
    const { width, height } = page.getSize()
    const fontSize = 12
    const font = await pdfDoc.embedFont(StandardFonts.Helvetica)
    const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold)
    const italicFont = await pdfDoc.embedFont(StandardFonts.HelveticaOblique)

    // Title
    page.drawText('RESELLER PRO SUBSCRIPTION CONTRACT', {
        x: 50,
        y: height - 50,
        size: 20,
        font: boldFont,
        color: rgb(0, 0, 0),
    })

    let y = height - 100

    const drawLine = (label: string, value: string) => {
        page.drawText(`${label}:`, { x: 50, y, size: fontSize, font: boldFont })
        page.drawText(value, { x: 200, y, size: fontSize, font })
        y -= 25
    }

    drawLine('Subscriber Name', data.userName)
    drawLine('Plan', data.planName)
    drawLine('Amount Paid', `INR ${data.amount}`)
    drawLine('Start Date', data.startDate)
    drawLine('End Date', data.endDate)

    y -= 20
    page.drawLine({
        start: { x: 50, y },
        end: { x: width - 50, y },
        thickness: 1,
        color: rgb(0, 0, 0),
    })
    y -= 40

    page.drawText('Terms and Conditions:', { x: 50, y, size: fontSize, font: boldFont })
    y -= 20
    page.drawText('1. This subscription is non-refundable.', { x: 50, y, size: 10, font })
    y -= 15
    page.drawText('2. ResellerPro reserves the right to terminate service for violation of terms.', { x: 50, y, size: 10, font })
    y -= 15
    page.drawText('3. Utilization of data is subject to the privacy policy.', { x: 50, y, size: 10, font })

    y -= 50
    page.drawText('Generated by ResellerPro System', { x: 50, y, size: 10, font: italicFont, color: rgb(0.5, 0.5, 0.5) })

    const pdfBytes = await pdfDoc.save()
    return Buffer.from(pdfBytes)
}
